data:
  dataset_name: sift
  max_elements: 1000000
  begin_num: 5000
  write_batch_size: 1000
  max_queries: 1000
  data_type: float
  data_path: ../data/sift/sift_base.bin
  query_path: ../data/sift/sift_query.bin

index:
  index_type: parlayhnsw
  m: 48
  ef_construction: 200
  level_m: 1.2
  alpha: 1.25

search:
  recall_at: 10
  ef_search: 50
  beam_width: 170
  visit_limit: 1000

workload:
  write_ratio: 0.2
  num_threads: 48
  queue_size: 100000
  query_new_data: false
  input_rate: 100000
  enforce_consistency: true

result:
  output_dir: ./result
  search_res_path: result/search_res.bin
  gt_path: ../data/sift/sift.gt20
  recall_tool_path: ../utils/build/calc_recall