data:
  dataset_name: sift
  max_elements: 1000000
  begin_num: 5000
  batch_size: 100
  max_queries: 10000
  data_type: float
  data_path: ../data/sift/sift_base.bin
  query_path: ../data/sift/sift_query.bin

index:
  index_type: parlayhnsw
  m: 32
  lb: 200

search:
  recall_at: 10
  ls: 50

workload:
  write_ratio: 0.5
  num_threads: 16
  queue_size: 20000
  query_new_data: false
  input_rate: 1000
  enforce_consistency: true

result:
  output_dir: ./result
  gt_path: ./result/gt.txt
  batch_res_path: ./result/batch_res.txt