data:
  dataset_name: sift
  max_elements: 1000000
  begin_num: 5000
  write_batch_size: 100
  max_queries: 10000
  data_type: float
  data_path: ../data/sift/sift_base.bin
  query_path: ../data/sift/sift_query.bin

index:
  index_type: hnsw
  m: 32
  lb: 200

search:
  recall_at: 10
  ls: 50

workload:
  write_ratio: 1
  num_threads: 48
  queue_size: 1000
  query_new_data: false
  input_rate: 10000
  enforce_consistency: true

result:
  search_res_path: result/search_res.bin
  gt_path: ../data/sift/sift.gt20
  recall_tool_path: ../utils/build/calc_recall